# Generated by Django 3.2.7 on 2021-10-31 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='payment',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='students',
            name='fees',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Salary',
            field=models.IntegerField(),
        ),
    ]
