# Generated by Django 3.2.7 on 2021-10-31 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20211031_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='students',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='age',
            field=models.IntegerField(),
        ),
    ]
