# Generated by Django 3.2.7 on 2021-10-30 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('roll', models.IntegerField(unique=True)),
                ('city', models.CharField(max_length=20)),
                ('marks', models.IntegerField()),
                ('passdate', models.DateField()),
                ('admdate', models.DateTimeField()),
            ],
        ),
    ]
