# Generated by Django 3.2.8 on 2021-10-30 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
